[WIP]:Add branching for st2tests repo
StackStorm/st2cd pull request #211
Opened 2016-10-11 23:32 UTC by humblearner

2016-10-11 23:50 UTC, m4dcoder commented
LGTM

2016-10-13 18:55 UTC, lakshmi-kannan requested changes

2016-10-13 18:55 UTC, lakshmi-kannan commented on actions/setup_e2e_tests.sh
> +    git clone -b ${VERSION} --depth 1 https://github.com/StackStorm/st2tests.git
Why do we need this git clone and st2 run packs.install in line 39?

2016-10-13 18:55 UTC, lakshmi-kannan commented on actions/setup_e2e_tests.meta.yaml
> +  version:
Should be called branch to avoid confusions

2016-10-13 18:55 UTC, lakshmi-kannan commented on actions/setup_e2e_tests.sh
> +   git clone -b v${VERSION} --depth 1 https://github.com/StackStorm/st2tests.git
What if someone supplies 2.0.1 as version? Our branches are v2.0 etc.

2016-10-13 18:58 UTC, humblearner commented on actions/setup_e2e_tests.sh
> +    git clone -b ${VERSION} --depth 1 https://github.com/StackStorm/st2tests.git
git clone is for robotfm tests and st2 run packs.install is for all the other packs. Well we need to make robotfm pack eventually :)

2016-10-13 19:50 UTC, humblearner commented on actions/setup_e2e_tests.meta.yaml
> +  version:
done!!

2016-10-13 19:51 UTC, humblearner commented on actions/setup_e2e_tests.sh
> +   git clone -b v${VERSION} --depth 1 https://github.com/StackStorm/st2tests.git
https://github.com/StackStorm/st2cd/pull/211/files#diff-b585755378dcc390127e7d68b1360256R5

2016-10-14 20:00 UTC, lakshmi-kannan approved these changes

2016-10-14 20:01 UTC, lakshmi-kannan commented
LGTM. Merge and deploy and see things 🔥

2016-10-14 20:47 UTC, merged