Update packer_st2 changeling, commit and tag
StackStorm/st2cd pull request #332
Opened 2018-05-11 00:16 UTC by warrenvw

Easier and faster to perform the above tasks in one action, although it would be nice to re-use the tag-release action.

2018-05-11 01:45 UTC, arm4b requested changes
Left several comments,

But before merging, please try to run action (from `st2cicd` server) to produce a test release and verify if it works OK.

2018-05-11 01:45 UTC, armab commented on actions/workflows/st2_finalize_release.yaml
> +        update_packer_st2_changelog_and_tag:
Let's follow already established naming following the `mistral_tag_release`

eg `vagrant_tag_release` to make it more clear.

2018-05-11 01:45 UTC, armab commented on actions/workflows/st2_finalize_release.yaml
> +                version: <% $.version + '_' + $.utc_date %>
Version should be in `v2.7.1-20180131` format

2018-05-11 01:45 UTC, armab commented on actions/update_changelog.meta.yaml
> +name: update_changelog
Because we create git tag (which is more important for release, comparing to changelog), I think we'll need a better naming for this action.

2018-05-11 08:04 UTC, warrenvw commented
I'll test in the morning.

2018-05-11 11:45 UTC, arm4b approved these changes
The code LGTM, considering it'll be tested manually.

2018-05-12 04:39 UTC, merged

2018-05-12 14:07 UTC, armab commented
@warrenvw Great work with the release automation :+1: 
Just a reminder to st2 pack install this updated repo on st2cicd.