Additional fixes to the dockerfiles workflows
StackStorm/st2cd pull request #363
Opened 2018-12-18 19:15 UTC by warrenvw

A few changes to fix the workflows for `st2-dockerfiles` and `st2enterprise-dockerfiles`.

2018-12-18 20:04 UTC, m4dcoder requested changes

2018-12-18 20:04 UTC, m4dcoder commented on actions/st2_chg_ver_for_st2_dockerfiles.sh
> +BRANCH="v${SHORT_VERSION}"
I prefer the branch to be passed explicitly into the script.  All of the other st2_cfg_ver_*.sh scripts pass the branch into the script. You can use YAQL expression to get the short version to pass in from the workflow.

2018-12-19 02:29 UTC, warrenvw commented on actions/st2_chg_ver_for_st2_dockerfiles.sh
> +BRANCH="v${SHORT_VERSION}"
I've addressed your comments in a5a83e6, and also fixed a few additional issues...

2018-12-19 21:13 UTC, m4dcoder approved these changes
LGTM. Thanks for being diligent.

2018-12-19 21:16 UTC, merged